config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :registrations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home_page#index'

  resources :theatrepages
  resources :blogpages
  resources :lifepages
  resources :codingpages
  resources :educationpages
  resources :contactpages
  resources :workpages
  resources :trainingpages
  resources :headshotpages
  resources :productionpages
  resources :news
  resources :auditionsides
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/blogpage.rb
class Blogpage < ApplicationRecord
end

app/models/codingpage.rb
class Codingpage < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/educationpage.rb
class Educationpage < ApplicationRecord
end

app/models/lifepage.rb
class Lifepage < ApplicationRecord
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :picture, ImageUploader
end

app/models/theatrepage.rb
class Theatrepage < ApplicationRecord
	mount_uploader :picture, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
	def index

	end
end

app/controllers/productionpages_controller.rb
class ProductionpagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogpages_helper.rb
module BlogpagesHelper
end

app/helpers/codingpages_helper.rb
module CodingpagesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/lifepages_helper.rb
module LifepagesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/productionpages_helper.rb
module ProductionpagesHelper
end

app/helpers/theatrepages_helper.rb
module TheatrepagesHelper
end

app/helpers/workpages_helper.rb
module WorkpagesHelper
end

app/views/productionpages/index.html.erb
<hr>
<h2> <%= link_to 'PERFORMANCE', theatrepages_path %> </h2>
<h3> Credits </h3>
<hr>
<br />
<div class="row feature2 text-center">
	<div class="educationfeature col-12 col-sm">
		<div class="featurephoto col-12 col-sm">
			<%= image_tag 'kissmekate.jpg', class: 'd-block img-fluid' %>
		</div>
		<div class="feature col-12 col-sm">
			<br />
			<br />
			<h3> Lilli/Katherine </h3>
			<h4> Kiss Me, Kate! </h4>
			<h5> Sopris Theatre Company (CMC) </h5>
			<body> 2020 </body>
		</div>
	</div>
	<br />
	<div class="educationfeature col-12 col-sm">
		<div class="featurephoto col-12 col-sm">
			<%= image_tag 'taketen2020.jpg', class: 'd-block img-fluid' %>
		</div>
		<div class="feature col-12 col-sm">
			<br />
			<br />
			<h3> Main Annika </h3>
			<h4> The Bench Grinder </h4>
			<h5> Theatre Masters Take Ten </h5>
			<body> 2020 </body>
		</div>
	</div>
</div>
<br />
<div class="row feature2 text-center">
	<div class="educationfeature col-12 col-sm">
		<div class="featurephoto col-12 col-sm">
			<%= image_tag 'doralee.jpg', class: 'd-block img-fluid' %>
		</div>
		<div class="feature col-12 col-sm">
			<br />
			<br />
			<h3> Doralee Rhodes </h3>
			<h4> 9 to 5 (the Musical) </h4>
			<h5> Aspen Community Theatre </h5>
			<body> 2019 </body>
		</div>
	</div>
	<br />
	<div class="educationfeature col-12 col-sm">
		<div class="featurephoto col-12 col-sm">
			<%= image_tag 'taketen2019.jpg', class: 'd-block img-fluid' %>
		</div>
		<div class="feature col-12 col-sm">
			<br />
			<br />
			<h3> Emma/Waitress </h3>
			<h4> SEND/The Blind Date </h4>
			<h5> Theatre Masters Take Ten </h5>
			<body> 2019 </body>
		</div>
	</div>
</div>
<br />
<div class="row feature2 text-center">
	<div class="educationfeature col-12 col-sm">
		<div class="featurephoto col-12 col-sm">
			<%= image_tag 'vaude.jpg', class: 'd-block img-fluid' %>
		</div>
		<div class="feature col-12 col-sm">
			<br />
			<br />
			<h3> Vaudevillian </h3>
			<h4> Vaudeville Holiday Show </h4>
			<h5> Glenwood Vaudeville Review </h5>
			<body> 2018-19 </body>
		</div>
	</div>
	<br />
	<div class="educationfeature col-12 col-sm">
		<div class="featurephoto col-12 col-sm">
			<%= image_tag 'bigriver.jpg', class: 'd-block img-fluid' %>
		</div>
		<div class="feature col-12 col-sm">
			<br />
			<br />
			<h3> Mary Jane </h3>
			<h4> Big River </h4>
			<h5> Aspen Community Theatre </h5>
			<body> 2018 </body>
		</div>
	</div>
</div>
<br />
<div class="row feature2 text-center">
	<div class="educationfeature col-12 col-sm">
		<div class="featurephoto col-12 col-sm">
			<%= image_tag 'londonpineapple.jpg', class: 'd-block img-fluid' %>
		</div>
		<div class="feature col-12 col-sm">
			<br />
			<br />
			<h3> Performer </h3>
			<h4> PPAS Showcase </h4>
			<h5> Pineapple Preforming Arts – London </h5>
			<body> 2017 </body>
		</div>
	</div>
	<br />
	<div class="educationfeature col-12 col-sm">
		<div class="featurephoto col-12 col-sm">
			<%= image_tag 'koenigin.jpg', class: 'd-block img-fluid' %>
		</div>
		<div class="feature col-12 col-sm">
			<br />
			<br />
			<h3> Opera Chorus </h3>
			<h4> Die Königin von Saba </h4>
			<h5> Stadttheatre Freiburg </h5>
			<body> 2015 </body>
		</div>
	</div>
</div>
<br />
<br />
<br />