config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :registrations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home_page#index'

  resources :theatrepages
  resources :blogpages
  resources :lifepages
  resources :codingpages
  resources :educationpages
  resources :contactpages
  resources :workpages
  resources :trainingpages
  resources :headshotpages
  resources :productionpages
  resources :news
  resources :auditionsides
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/blogpage.rb
class Blogpage < ApplicationRecord
end

app/models/codingpage.rb
class Codingpage < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/educationpage.rb
class Educationpage < ApplicationRecord
end

app/models/lifepage.rb
class Lifepage < ApplicationRecord
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :picture, ImageUploader
end

app/models/theatrepage.rb
class Theatrepage < ApplicationRecord
	mount_uploader :picture, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
	def index

	end
end

app/controllers/theatrepages_controller.rb
class TheatrepagesController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create]

	def index

	end

	def show
		@theatrepage = Theatrepage.all
	end

	def new
		@theatrepage = Theatrepage.new
	end 

	def create
		@theatrepage = Theatrepage.create(theatrepage_params)
	    if @theatrepage.valid?
      		redirect_to theatrepages_path
    	else
      		render :new, status: :unprocessable_entity
    	end
	end

	private 

	def theatrepage_params
	    params.require(:theatrepage).permit(:picture)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auditionsides_helper.rb
module AuditionsidesHelper
end

app/helpers/blogpages_helper.rb
module BlogpagesHelper
end

app/helpers/codingpages_helper.rb
module CodingpagesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/headshotpages_helper.rb
module HeadshotpagesHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/lifepages_helper.rb
module LifepagesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/theatrepages_helper.rb
module TheatrepagesHelper
end

app/helpers/workpages_helper.rb
module WorkpagesHelper
end

app/views/theatrepages/index.html.erb
<hr>
<h2> PERFORMANCE </h2>
<h3>
	<%= link_to 'Vocal Training', trainingpages_path %> | <%= link_to 'Credits', productionpages_path %> | <%= link_to 'Headshots', headshotpages_path %> | <%= link_to 'Audition Sides', auditionsides_path %> | <%= link_to 'Contact', contactpages_path %> | <%= link_to 'News', news_index_path %> 
</h3>
<hr>
<div class="row feature2 text-center">
	<div class="feature3 col-12 col-sm">
		<iframe width="560" height="315" src="https://www.youtube.com/embed/RDZiOctdobg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	</div>
	<br />
	<div class="feature3 col-12 col-sm">
		<iframe width="560" height="315" src="https://www.youtube.com/embed/4XZvaZ6Qqd8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	</div>
</div>
<div class="row feature2 text-center">
	<div class="feature3 col-12 col-sm">
		<iframe width="560" height="315" src="https://www.youtube.com/embed/G4ekYPb6toc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	</div>
	<br />
	<div class="feature3 col-12 col-sm">
		<iframe width="560" height="315" src="https://www.youtube.com/embed/x1lBwjCjpBk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	</div>
</div>
<div class="row feature2 text-center">
	<div class="feature3 col-12 col-sm">
		<iframe width="560" height="315" src="https://www.youtube.com/embed/ZYhyLtj_vCM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	</div>
	<br />
	<div class="feature3 col-12 col-sm">
		<iframe width="100%" height="100px" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/777853717%3Fsecret_token%3Ds-n1My7&color=%237b5c47&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
		<iframe width="100%" height="100px" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/777853711%3Fsecret_token%3Ds-GILsB&color=%237b5c47&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
		<iframe width="100%" height="100px" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/777853702%3Fsecret_token%3Ds-C3kfP&color=%237b5c47&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe></iframe>
	</div>	
</div>
<div class="row feature2 text-center">
	<div class="feature3 col-12 col-sm">
		<iframe width="560" height="315" src="https://www.youtube.com/embed/EKRNKEBrMJI" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	</div>
	<br />
	<div class="feature3 col-12 col-sm">
		<iframe width="560" height="315" src="https://www.youtube.com/embed/WCguJV1rGjs" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	</div>
</div>
<div class="row feature2 text-center">
	<div class="feature3 col-12 col-sm">
		<iframe width="560" height="315" src="https://www.youtube.com/embed/RPjYoOwIoMk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	</div>
	<br />
	<div class="feature3 col-12 col-sm">
		<iframe width="560" height="315" src="https://www.youtube.com/embed/ArFYFS94BHw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	</div>
</div>
<div class="row feature2 text-center">
	<div class="feature3 col-12 col-sm">
		<iframe width="560" height="315" src="https://www.youtube.com/embed/9Ab_gQCK0aU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	</div>
	<br />
	<div class="feature3 col-12 col-sm">
		<iframe width="560" height="315" src="https://www.youtube.com/embed/ec1P1_BSpWs" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	</div>
</div>
<div class="row feature2 text-center">
	<div class="feature3 col-12 col-sm">
		<iframe width="560" height="315" src="https://www.youtube.com/embed/ng3ZGSq2UvE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	</div>
	<br />
	<div class="feature3 col-12 col-sm">
		<iframe width="560" height="315" src="https://www.youtube.com/embed/3sGF3Ta5Eqs" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	</div>
</div>
<div class="row feature2 text-center">
	<div class="feature3 col-12 col-sm">
		<iframe width="560" height="315" src="https://www.youtube.com/embed/4G41muRlx9g" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	</div>
	<br />
	<div class="feature3 col-12 col-sm">
		<iframe width="560" height="315" src="https://www.youtube.com/embed/zqgyrOIlp_U" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	</div>
</div>

app/views/theatrepages/new.html.erb
<div class="booyah-box col-10 offset-1">
	<h1> Upload Content </h1>
	<%= simple_form_for @theatrepage do |f| %>
	  <%= f.input :picture %>
	  <%= f.input :caption %>
	  <%= f.submit "Add a Picture", class: 'btn btn-primary' %>
	<% end %> 
</div>