config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :registrations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home_page#index'

  resources :theatrepages
  resources :blogpages
  resources :lifepages
  resources :codingpages
  resources :educationpages
  resources :contactpages
  resources :workpages
  resources :trainingpages
  resources :headshotpages
  resources :productionpages
  resources :news
  resources :auditionsides
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/blogpage.rb
class Blogpage < ApplicationRecord
end

app/models/codingpage.rb
class Codingpage < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/educationpage.rb
class Educationpage < ApplicationRecord
end

app/models/lifepage.rb
class Lifepage < ApplicationRecord
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :picture, ImageUploader
end

app/models/theatrepage.rb
class Theatrepage < ApplicationRecord
	mount_uploader :picture, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
	def index

	end
end

app/controllers/workpages_controller.rb
class WorkpagesController < ApplicationController
	def index
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auditionsides_helper.rb
module AuditionsidesHelper
end

app/helpers/blogpages_helper.rb
module BlogpagesHelper
end

app/helpers/codingpages_helper.rb
module CodingpagesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/lifepages_helper.rb
module LifepagesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/theatrepages_helper.rb
module TheatrepagesHelper
end

app/helpers/workpages_helper.rb
module WorkpagesHelper
end

app/views/workpages/index.html.erb
<hr>
<h2> 
	<%= link_to 'WEB DESIGN', codingpages_path %> 
</h2>
<h3> WORK </h3>
<hr>
<div class="educationfeature col-12 col-sm">
	<br />
	<h3> House Manager </h3>
	<hr width="25%">
	<h3> Aspen Music Festival and School </h3>
	<h4> June 2019 - Present </h4>
	<body> 
		Manage the Benedict Music Tent and Harris Hall during concerts/events. Help facilitate smooth events, manage ushers, admissions, and other assorted tasks. 
		<br />
	</body>
</div>
<br />
<div class="educationfeature col-12 col-sm">
	<br />
	<h3> Server/Hostess/Farmshop Helper </h3>
	<hr width="25%">
	<h3> Meat and Cheese Aspen </h3>
	<h4> May - August 2017 and August 2018 - Present </h4>
	<body> 
		Maintain excellent customer service to sell food and market products. 
		<br />
	</body>
</div>
<br />
<div class="educationfeature col-12 col-sm">
	<br />
	<h3> Director </h3>
	<hr width="25%">
	<h3> Aspen School District</h3>
	<h4> October 2018 - Present </h4>
	<body> 
		Direct children to produce school productions, show promotion, and graphic design. 
		<br />
	</body>
</div>
<br />
<div class="educationfeature col-12 col-sm">
	<br />
	<h3> Teaching Artist/ Stage Manager </h3>
	<hr width="25%">
	<h3> Theatre Aspen </h3>
	<h4> January 2019 - Present </h4>
	<body> 
		Stage Managing for youth productions while maintaining theatre etiquette/safety. 
		<br />
	</body>
</div>
<br />
<div class="educationfeature col-12 col-sm">
	<br />
	<h3> Office Assistant </h3>
	<hr width="25%">
	<h3> Bandana Kids </h3>
	<h4> December 2019-Present </h4>
	<body> 
		Coordination of inventory, purchase orders, IT inquiries, social media. 
		<br />
	</body>
</div>
<br />
<div class="educationfeature col-12 col-sm">
	<br />
	<h3> Social Media Intern </h3>
	<hr width="25%">
	<h3> Rejuce </h3>
	<h4> December 2017 - May 2018 </h4>
	<body> 
		Manage and plan social media posts for Instagram/Twitter/Facebook/Website. 
		<br />
	</body>
</div>
<br />
<div class="educationfeature col-12 col-sm">
	<br />
	<h3> Sales Person </h3>
	<hr width="25%">
	<h3> Leaf People- Organic Skincare </h3>
	<h4> May 2017 - March 2018 </h4>
	<body> 
		Manage online marketing and shop inventory and promotion of products. 
		<br />
	</body>
</div>
<br />